From YouTube https://www.youtube.com/watch?v=Z_ikDlimN6A, starting chapter 12.

In [ ]:
!nvidia-smi

Mon Oct 13 11:07:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   59C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device("cpu")
print(f"Torch device: {device}")
if torch.cuda.is_available():
  print(f"Using CUDA device: {torch.cuda.get_device_name(0)}")

Torch device: cuda
Using CUDA device: Tesla T4


In [ ]:
%%time
tensor = torch.rand(1000000, device=torch.device("cpu"))
tensor = tensor * 10
tensor.shape, tensor.device


CPU times: user 6.72 ms, sys: 2.98 ms, total: 9.69 ms
Wall time: 9.9 ms


(torch.Size([1000000]), device(type='cpu'))

In [ ]:
%%time
tensor = torch.rand(1000000, device=torch.accelerator.current_accelerator())
tensor = tensor * 10
tensor.shape, tensor.device

CPU times: user 913 µs, sys: 0 ns, total: 913 µs
Wall time: 638 µs


(torch.Size([1000000]), device(type='cuda', index=0))

In [ ]:
tensor = torch.tensor([[1,2],
                       [3,4],
                       [5,6],
                       [7,8]])
tensor, tensor.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 torch.Size([4, 2]))

In [ ]:
tensor.reshape([2,4])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [ ]:
tensor.reshape([1,8])

tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
tensor.view([-1,4])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [ ]:
tensor = tensor.reshape([1,2,4])
tensor, tensor.shape

(tensor([[[1, 2, 3, 4],
          [5, 6, 7, 8]]]),
 torch.Size([1, 2, 4]))

In [ ]:
squeezed = tensor.squeeze()

squeezed, squeezed.shape

(tensor([[1, 2, 3, 4],
         [5, 6, 7, 8]]),
 torch.Size([2, 4]))

In [ ]:
unsqueezed = squeezed.unsqueeze(1)
unsqueezed, unsqueezed.shape

(tensor([[[1, 2, 3, 4]],
 
         [[5, 6, 7, 8]]]),
 torch.Size([2, 1, 4]))

In [ ]:
# rearrange colour from 3rd to 1st dimension
image = torch.rand(size=(255,255,3))
image.shape

torch.Size([255, 255, 3])

In [ ]:
# specifies the dimension index from the original image for the new *view*
image.permute(2,0,1).shape

torch.Size([3, 255, 255])

In [ ]:
tensor = torch.arange(1,10).reshape(1,3,3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor[0,0,:]

tensor([1, 2, 3])

In [ ]:
tensor[0,2,2]

tensor(9)

In [ ]:
tensor[0,:,2]

tensor([3, 6, 9])